=== AnnaLub/JavaExternal_06_03_2018/MySQLLab/data/teachers.xsd
<?xml version="1.0" encoding="UTF-8" ?>
<schema xmlns="http://www.w3.org/2001/XMLSchema"
        targetNamespace="http://example.com/teachers"
        xmlns:tns="http://example.com/teachers"
        elementFormDefault="qualified">
    <element name="teachers">
        <complexType>
            <sequence>
                <element name="teacher"
                         type="tns:Teacher"
                         minOccurs="2"
                         maxOccurs="unbounded" />
            </sequence>
        </complexType>
    </element>
    <complexType name="Teacher">
        <sequence>
            <element name="name" type="string" />
            <element name="status" type="string" />
        </sequence>
    </complexType>
</schema>

=== AnnaLub/JavaExternal_06_03_2018/MySQLLab/data/teachers.xml
<teachers xmlns:xsi = "http://www.w3.org/2001/XMLSchema-instance"
         xmlns = "http://example.com/teachers"
         xsi:schemaLocation = "http://example.com/teachers teachers.xsd">
    <teacher>
        <name>TEACHER ONE</name>
        <status>SENIOR</status>
    </teacher>
    <teacher>
        <name>TEACHER TWO</name>
        <status>PROFESSOR</status>
    </teacher>
    <teacher>
        <name>TEACHER THREE</name>
        <status>INTERN</status>
    </teacher>
</teachers>

=== AnnaLub/JavaExternal_06_03_2018/2Max_Veres_completed tasks/MySQLLab/data/teachers.xml
<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<teachers xmlns="http://example.com/teachers" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://example.com/teachers teachers.xsd">
    <teacher>
        <name>TEACHER ONE</name>
        <status>XML CRUD</status>
    </teacher>
    <teacher>
        <name>TEACHER TWO</name>
        <status>XML CRUD</status>
    </teacher>
    <teacher>
        <name>TEACHER THREE</name>
        <status>XML CRUD</status>
    </teacher>
</teachers>
